name: form_gemini_tutorial
description: "Una aplicación Flutter para formularios complejos con integración backend."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
    
  # Formularios y validación
  flutter_form_builder: ^10.2.0 
  form_builder_validators: ^11.2.0
  
  # Comunicación con backend
  dio: ^5.4.3+1
  
  # Persistencia y caché
  shared_preferences: ^2.2.3
  
  # Gestión de estado
  provider: ^6.1.2
  
  # Networking y logs
  pretty_dio_logger: ^1.3.1
  
  # Manejo de fechas
  intl: 0.20.2
  json_annotation: ^4.9.0

  # Configuración de entorno
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Generación de código para JSON
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  
  # Testing
  mockito: ^5.4.4
  
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
  
  # Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700